@startuml

participant "Client" as Client
participant "Server" as Server

participant "User defined\nexecution method" as User



activate Client
activate Server
Client -> Server : goal request
Server --> Client : goal response (accept)

' group result request
    Server -> User : /handle_goal
    activate User
    Client ->> Server : result request
    User --> Client : publish feedback
    User --> Client : publish feedback
    Client -> Server : cancel request
    Server -> User : /handle_cancel
    User --> Client : publish feedback
    User --> Server : set result
    deactivate User
' end
Server -->> Client : result response
@enduml